/*eslint olblint/image-names:0
         olblint/hardcoded-fonticons-values:0
*/
define([], function () {

    var VIEW_CONSTANTS = {
       // LINK_TO_DBX: 'https://dbx.kony.com/products-and-solutions/consumer-lending',
        IMAGES : {
         //    BANNER_IMAGE: 'http://pmqa.konylabs.net/KonyWebBanking/banner_img.png',
         //    DESKTOP_BANNER_IMAGE: 'https://retailbanking1.konycloud.com/dbimages/banner-add-mob.png',
         //    MOBILE_BANNER_IMAGE: 'https://retailbanking1.konycloud.com/dbimages/banner-ad-tab.png',
          TABLET_BANNER_IMAGE:'banner_ad_tab1.png',
            BUTTON_UP: "bbupicon_1.png",
            BUTTON_DOWN: "bbdownicon_1.png",
            SORTING_NEXT: 'sorting_next.png',
            SORTING_PREVIOUS: 'sorting_previous.png',
            SORTING: 'sorting.png',
            CHECKED_IMAGE: "checked_box.png",
            UNCHECKED_IMAGE: "unchecked_box.png",
            ARRAOW_UP : "chevron_up.png",
            ARRAOW_DOWN : "arrow_down.png",
          	ACTIVE_UP : "active_up_btn.png",
          	DISABLE_UP : "disable_up_btn.png",
          	ACTIVE_DOWN : "active_down_btn.png",
          	DISABLE_DOWN : "disable_down_btn.png",
            EAZEE_FOOD_CARD: 'eazee_food_card.png',
            GOLDEN_CARD: 'golden_card.png',
            PETRO_CARD: 'petro_card.png',
            PLATINUM_CARD: 'platinum_card.png',
            PREMIUM_CLUB_CREDIT: 'premium_club_credit.png',
            SHOPPING_CARD: 'shopping_card.png',
           	EAZEE_FOOD_CARDS: 'eazee_food_cards.png',
            GOLDEN_CARDS: 'golden_cards.png',
            PETRO_CARDS: 'petro_cards.png',
            PLATINUM_CARDS: 'platinum_cards.png',
            PREMIUM_CLUB_CREDITS: 'premium_club_credits.png',
            SHOPPING_CARDS: 'shopping_cards.png',
            RADIOBTN_ACTIVE_SMALL: 'radiobtn_active_small.png',
            RADIO_BTN_ACTIVE: 'radio_butn_active.png',
			RADIO_BTN_INACTIVE: 'radio_btn_inactive.png',
            ICON_RADIOBTN: 'icon_radiobtn.png',
            ICON_RADIOBTN_ACTIVE: 'radio_butn_active.png',
            PAGINATION_NEXT_ACTIVE: 'pagination_next_active_container.png',
            PAGINATION_NEXT_INACTIVE: 'pagination_next_inactive.png',
            PAGINATION_BACK_ACTIVE: 'pagination_back_blue_container.png',
            PAGINATION_BACK_INACTIVE: 'pagination_back_inactive.png',
            LOGOUT_TICK_MARK: 'logout_tick_mark.png',
            SESSION_TIMEOUT_WHITE:'session_timeout_white.png',
            DEFAULT_USERNAME: 'default_username.png',
            USERNAME: 'username.png',
            CHEVRON_DOWN_WHITE: 'chevron_down_white.png',
          	SEARCH_IMAGE:'search_blue.png',
            LOGIN_USERNAME_ICON: 'login_username_icon.png',
            USER_IMAGE: 'user_image.png',
			BULKPAY_PENDING:'bulk_pay_unsuccessfull.png',
			BULKPAY_SUCCESS : 'bulk_billpay_success.png',
            BULKPAY_UNSUCCESS: 'close_red.png',
            SUCCESS_GREEN: "success_green.png",
            WARNING_MSG : "error_yellow_2.png",
            SEARCH_BLUE: "search_blue.png",
            SELECTED_SEARCH: 'selecetd_search.png',
			KONYBANK_ACC: 'to_konybank_acc.png',
            OTHERKONYBANK_ACC: 'to_otherkonybank_acc.png',
            OTHERBANK_ACC: 'to_otherbank_acc.png',
            INTERNATIONALBANK_ACC: "to_internationalbank_acc.png",
            WIRE_TRANSFER_ACC: "wire_transfer.png",
            CHEVRON_UP: "chevron_up.png",
            ARROW_UP : "arrow_up.png",
            ARROW_DOWN : "arrow_down.png",
            ARROW_LEFT_GREY : "arrow_left_grey.png",
            BANK_ICON : "bank_icon.png",
            ACCOUNTS_SIDEBAR_BLUE : "accounts_sidebar_blue.png",
            BANK_ICON_BLUE : "bank_icon_blue.png",
            ATM_ICON_BLUE : "atm_icon_blue.png",
            TRANSACTION_TYPE_WITHDRAWL : "transaction_type_withdrawl.png",
            RADIO_BUTTON_ACTIVE : "radiobtn_active.png",
            BANK_IMG_ROUNDED : "bank_img_rounded.png",
            ATTACHMENT_GREY : 'attachment_grey.png',
            DOWNLOAD_BLUE:'bbdownloadicon_1.png',
            REPLY_ARROWTIP_RIGHT:'reply_arrowtip_right.png',
            REPLY_ARROWTIP: 'reply_arrowtip.png',
            BANK_CIRCLE_ICON_MOD: 'bank_circle_icon_mod.png',
            ICON_CLOSE_GREY :'icon_close_grey.png',
          	ICON_CLOSE_BLUE :'bbcloseicon.png',
            PDF_IMAGE: 'pdf_image.png',
            CSV_IMAGE: 'csv_image.png',
			XLS_IMAGE: 'xlsx_image.png',
            TXT_IMAGE:'txt_image.png',
            JPEG_IMAGE:'jpeg_image.png',
            DOC_IMAGE:'doc_image.png',
            DOCX_IMAGE :'docx_image.png',
            PNG_IMAGE:'png_image.png',
            NUO_SAVINGS:'nuo_savings.png',
            PAGEOFFDOT:'pageoffdot.png',
            SIDEBAR_TURQUOISE: 'accounts_sidebar_turquoise.png',
            SIDEBAR_PURPLE: 'accounts_sidebar_purple.png',
            SIDEBAR_YELLOW: 'accounts_sidebar_yellow.png',
            SIDEBAR_BLUE: 'accounts_sidebar_blue.png',
            SIDEBAR_BROWN: 'accounts_sidebar_brown.png',
            FEEDBACK_ICON: 'feedback_icon.png' ,
            INFO_GREY: 'info_grey.png',
            NUO_CREDIT_CHECK_FAILURE:'nuo_credit_check_failure',
            NUO_SIGNATURE_MOBILE:'nuo_signature_mobile.png',
			FEEDBACK_ICON_GREY: 'feedback_icon_grey.png',
            FEEDBACK_ICON_FILLED: 'feedback_icon_filled.png',
            CIRCLE_BLUE_FILLED: 'circle_blue_filled.png',
            CIRCLE_UNFILLED: 'circle_unfilled.png',
            APP_STORE: 'appstore_2x.png',
            PLAY_STORE: 'google_play_2x.png',
            NOTIFICATION_FLAG: "notification_flag.png",
            NOTIFICATION_ICON: "notification_icon.png",
            ACTIVE_STATUS:'bb_user_active.png',
            SUSPEND_STATUS:'bb_user_suspended.png',
            NEW_STATUS:'New_Activation_link.png',
            USER_DEFAULT_IMAGE:'profile_header.png',
            USER_GREY_IMAGE:'profile_image_grey.png',
          	HDFC_BANK_IMAGE:'bank_icon_hdfc.png',
          	CITI_BANK_IMAGE:'bank_icon_citi.png',
          	BOA_BANK_IMAGE:'bank_icon_boa.png',
          	CHASE_BANK_IMAGE:'bank_icon_chase.png',
            INFINITY_BANK_IMAGE:'bank_icon_infinity.png',
            EXTERNAL_BANK_IMAGE:'bank_icon_external.png',
            SORT_FINAL_IMAGE: 'sortingfinal.png',
            SORT_NEXT_IMAGE: 'sorting_next.png',
            SORT_PREV_IMAGE: 'sorting_previous.png'
        },
        SKINS: {
            RECURRENCE_FIELD_FAST_TRANSFER: 'sknSSP42424215PxBorderE3E3E3',
            RADIO_BUTTON_NOT_FONT_ICON: 'sknC0C0C020pxNotFontIcons',
            RADIO_BUTTON_FONT_ICON: 'sknLblFontTypeIcon3343e820px',
            CARDS_ACTIVE_STATUS_LANDING: 'sknLblActiveCard',
            CARDS_LOCKED_STATUS_LANDING: 'sknLblLockedCard',
            CARDS_REPORTED_LOST_STATUS_LANDING: 'sknLblLostCard',
            CARDS_REPLACE_REQUEST_SENT_STATUS_LANDING: 'sknLblLostCard',
            CARDS_CANCEL_REQUEST_SENT_STATUS_LANDING: 'sknLblLostCard',
            CARDS_CANCELLED_STATUS_LANDING: 'sknLblLostCard',
            CARDS_ISSUED_STATUS_LANDING: 'sknLblLostCard',
            CARDS_INACTIVE_STATUS_LANDING: 'sknLblLockedCard',
            CARDS_ACTIVE_STATUS_DETAILS: 'sknLblActiveCard',
            CARDS_LOCKED_STATUS_DETAILS: 'sknLblLockedCard',
            CARDS_REPORTED_LOST_STATUS_DETAILS: 'sknLblLockedCard',
            CARDS_REPLACE_REQUEST_SENT_STATUS_DETAILS: 'sknLblLockedCard',
            CARDS_CANCEL_REQUEST_SENT_STATUS_DETAILS: 'sknLblLockedCard',
            CARDS_CANCELLED_STATUS_DETAILS: 'sknLblLockedCard',
          	CARDS_RADIOBTN_LABEL_UNSELECTED: 'sknd3d3d320pxolbfonticons',
          	CARDS_RADIOBTN_LABEL_SELECTED: 'sknlblOLBFonts3343A820px',
            CARD_RADIOBTN_LABEL_SELECTED:'sknlblOLBFonts0273E420pxOlbFontIcons',
          	STOPPAYMENTS_UNSELECT_TAB: 'sknbtnfbfbfbBottomBordere3e3e3',
            STOPPAYMENTS_SELECT_TAB: 'sknbtnffffffNoBorder',
            STOPPAYMENTS_UNSELECT_HOVER: 'sknhoverbtnacc',
          	LOGIN_RESEND_OTP_DISABLED: 'sknBtnBlockedBg0SSP0273e3Pr40',
            LOGIN_RESEND_OTP_ENABLED: 'sknBtnSSP0273E317PxBg0',
            LOGIN_LANGUAGE: 'sknLabelSSP3343A813Px',
			USER_BUTTON_DISABLED : 'sknBtnBlockedBg0SSP0273e315px',
			USER_BUTTON_ENABLED : 'CopysknBBBtn2',
			USERNAME: 'sknlbl727272SSPReg15px',
            BREADCRUM: 'sknBtnSSP3343A813PxBg0',
            BLANK_SKIN_FLEX: 'slFboxmb',
            BLANK_SKIN_FLEX_POINTER: 'flxHoverSkinPointer',
            BLANK_SKIN_TOPMENU: 'sknFlxFFFFFbrdr3343a8Pointer',
            BLANK_SKIN_TOPMENU_HOVER: 'sknHoverTopmenu7f7f7pointer',
            ACCOUNT_SUMMARY_UNSELECTED: 'sknBtnAccountSummaryUnselected',
            RADIOBTN_SELECTED: 'sknLblFontTypeIcon3343e820pxMOD',
            RADIOBTN_UNSELECTED: 'sknC0C0C020pxNotFontIconsMOD',
            RADIOBTN_UNSELECTED_FONT: 'sknC0C0C020pxolbfonticons',
            ACCOUNT_SUMMARY_UNSELETED_MODIFIED: 'sknBtnAccountSummaryUnselected',
            ACCOUNT_SUMMARY_UNSELETED: 'sknBtnAccountSummaryUnselected',
            ACCOUNT_SUMMARY_SELETED_MODIFIED: 'sknBtnAccountSummarySelected',
            ACCOUNT_SUMMARY_SELETED: 'sknBtnAccountSummarySelected',
            BLOCKED: 'sknBtnBlockedSSP0273e315px',
            ACCOUNT_NUMBER_TEXTBOX: 'sknTextBox72',
            DISABLED: 'skndisabled',
            NORMAL: 'sknBtnNormalSSPFFFFFF15Px',
            HOVER: 'sknBtnNormalSSPFFFFFFHover15Px',
            FOCUS: 'sknBtnNormalSSPFFFFFF15PxFocus',
            CANCEL: 'sknBtnffffffBorder0273e315pxRadius2px',
            BORDER: 'skntxtSSP424242BorderFF0000Op100Radius2px',
            RED_TEXT: 'sknlblSSP5daf0b15px',
            ACCOUNT_TYPE_UNSELECTED : 'sknBtnAccountTypeUnselected',
			TAB_INACTIVE: 'sknBtnAccountSummaryUnselected',
            TAB_ACTIVE: "sknBtnAccountSummarySelected", 
            TAB_HOVER: 'sknhoverbtnacc',
            BUTTON_BLOCKED: 'sknBtnBlockedSSP0273e315px',
            BUTTON_ENABLED: 'sknBtnNormalSSPFFFFFF15Px',
            BUTTON_ENABLED_FOCUS: 'sknBtnNormalSSPFFFFFF15PxFocus',
            BUTTON_ENABLED_HOVER: 'sknBtnNormalSSPFFFFFFHover15Px',
            RADIO_BUTTON_UNSELECTED: 'sknC0C0C020pxNotFontIcons',
            RADIO_BUTTON_SELECTED: 'sknLblFontTypeIcon3343e820px',
            LOCATE_BUTTONSHARESEND : 'sknBtn3343a8Border3343a82pxOp100Radius2px',
            LOCATE_BTNSHARECANCEL : 'sknBtnffffffBorder3343a81pxRadius2px',
            LOCATE_BTNSHARESEND : 'sknBtnBlockedSSPFFFFFF15Px',
            SKNFLEXF9F9F9 : 'sknFlexF9F9F9',
            COPYSLFBOXL :'copyslfbox1',
            SKNBTNFBFBFBBOTTOMBORDERE3E3E3 : 'sknbtnfbfbfbBottomBordere3e3e3',
            SKNBTNFFFFFFNOBORDER : 'sknbtnffffffNoBorder',
            SKNFLXFFFFFFBORDER0 : 'sknFlxffffffBorder0',
            SKNSEGF9F9F9HOVER : 'sknsegf9f9f9hover',
            SKNFLEXROUNDEDBORDERFFFFFF3PX : 'sknFlexRoundedBorderFFFFFF3Px',
            SKNBTNEBILLACTIVE : 'sknbtnebillactive',
            SKNBTNIMGINACTIVEEBILL : 'sknBtnImgInactiveEbill',
            SKNBTNACCOUNTSUMMARYUNSELECTEDMODIFIED:'sknBtnAccountSummaryUnselected',
			LOGIN_AFTER_LOGOUT: 'sknFlexLoginAfterLogout',
            LANGUAGE1: 'sknLabelSSPffffff13',
            LANGUAGE2: 'sknLabelSSP3343A813Px',
            LOGIN_ERROR_BAKGROUND: 'sknFlexLoginErrorBackgroundKA',
            LOGIN_MAIN_BAKGROUND: 'sknFlexLoginMainBackgroundKA',
            SKNFLXF7F7F7 : 'sknFlxf7f7f7',
            SKNFLXE9EBEE : 'sknflxe9ebee',
            SKNFLXFFFFFF : 'sknFlxffffffmb',
            THREE_DOTS_IMAGE: 'sknLblFontType0273E320px',
            SAVINGS_SIDE_BAR:'sknflxhex26d0cecode',
            CHECKINGS_SIDE_BAR:'sknflxhex9060B7code',
            CREDIT_CARD_SIDE_BAR:'sknflxhexf4ba22code',
            DEPOSIT_SIDE_BAR:'sknflxhex4a90e2code',
            MORTGAGE_CARD_SIDE_BAR:'sknflxhex8D6429code',
            LOAN_SIDE_BAR:'sknflxhex8D6429code',
            FEEDBACK_TOP_MENU_BLANK:'sknLblffffff15pxSSP',
            ACCOUNT_DETAILS_IDENTIFIER_SAVINGS: 'sknFlx26d0ceBorder1pxRound',
            ACCOUNT_DETAILS_IDENTIFIER_CHECKING: 'sknFlx9060b7Border1pxRound',
            ACCOUNT_DETAILS_IDENTIFIER_CREDIT_CARD: 'sknFlxf4ba22Border1pxRound',
            ACCOUNT_DETAILS_IDENTIFIER_DEPOSIT: 'sknFlx4a90e2Border1pxRound',
            ACCOUNT_DETAILS_IDENTIFIER_MORTGAGE: 'sknFlx8d6429Border1pxRound',
            ACCOUNT_DETAILS_IDENTIFIER_LOAN: 'sknFlx8d6429Border1pxRound',
            ACCOUNT_DETAILS_IDENTIFIER_UNCONFIGURED: 'sknFlx26D0CEOpacity20',
            RADIO_BTN_SELECTED:'sknLblFontTypeIcon0273e320px',

            
            ACCOUNTS_SAVINGS_ROW: 'sknFlx26D0CEOpacity20',
            ACCOUNTS_CHECKING_ROW: 'sknFlx9060b7Opacity20',
            ACCOUNTS_CREDITCARD_ROW: 'sknFlxF4BA22Opacity20',
            ACCOUNTS_DEPOSIT_ROW: 'sknFlx4A90E2Opacity20',
            ACCOUNTS_MORTGAGE_ROW: 'sknFlxBD6429Opacity20',
            ACCOUNTS_LOAN_ROW: 'sknFlxBD6429Opacity20',
            ACCOUNTS_UNCONFIGURED_ACCOUNT_ROW: 'sknFlx26D0CEOpacity20',
            ACCOUNTS_CSR_FAVOURITE_SELECTED: 'sknLblFontTypeIconff666612pxop50',
            ACCOUNTS_CSR_FAVOURITE_UNSELECTED: 'sknLblFontTypeIconcfcfcf12pxop50',
            ACCOUNTS_FAVOURITE_SELECTED: 'sknLblFontTypeIcon12px1a98ff',
            ACCOUNTS_FAVOURITE_UNSELECTED: 'sknLblFontTypeIcona0a0a012px',
            ACCOUNT_DETAILS_SUMMARY_SELECTED: 'sknBtnAccountSummarySelected',
            ACCOUNT_DETAILS_SUMMARY_SELECTED_HOVER: 'sknBtnAccountSummarySelectedHover',
            ACCOUNT_DETAILS_SUMMARY_UNSELECTED: 'sknBtnAccountSummaryUnselected',
            ACCOUNT_DETAILS_SUMMARY_UNSELECTED_HOVER: 'sknBtnAccountSummaryUnselectedHover',
            ACCOUNT_DETAILS_SUMMARY_HOVERED: 'sknBtnAccountSummarySelected',
            SKNCALTRANSACTIONS:'sknCalTransactions',
            SKNTBXLAT0FFFFFF15PXBORDER727272OPA20:'sknTbxSSPffffff15PxBorder727272opa20',
            BREADCRUMCSR:'sknBtnSSP3343A813PxBg0CSR',
            SKNBTN3343A8BORDER3343A82PXRADIUS2PX: 'sknBtn3343a8Border3343a82pxRadius2px',
            SKNBTNFFFFFFBORDER3343A81PXRADIUS2PXDISABLED:'sknBtnffffffBorder3343a81pxRadius2pxDisabled',
            SKNBTN3343A8BORDER3343A82PXRADIUS2PXDISABLED: 'sknBtn3343a8Border3343a82pxRadius2pxDisabled',
            SKNFF0000CAL: 'sknff0000Cal',
            SKNTXTSSP424242BORDERFF0000OP100RADIUS2PX:'skntxtSSP424242BorderFF0000Op100Radius2px',
			PAYDUE_DUE_AMOUNT: 'skntbx727272SSP15Opacity20',
            PAYDUE_OTHER_AMOUNT: 'sknTbxSSPffffff15PxBorder727272opa20',
            PAYDUE_ACCOUNT_SAVINGS: 'sknFlx26D0CE',
            PAYDUE_ACCOUNT_CHECKING: 'sknFlx9060b7',
            PAYDUE_ACCOUNT_CREDITCARD: 'sknFlxF4BA22',
            ENROLL_RESETSUCCESS: 'sknLblSSP42424217px',
            FEEDBACK_LABELFEEDBACK: 'sknLabelSSP5f5f5f15px',
            SEARCH_DISABLED: 'sknBtnNormalSSPFFFFFF15PxCSR',
            FLEX_GRADIENT_BLUE_WHITE:'sknflxGradient0273e3ffffff',
            FLEX_GRADIENT_WHITE_BLUE:'sknflxGradientffffff0273e3',
            FONT_ICON_BLUE:'sknlblfonticon17px0273e3',
            FONT_ICON_WHITE:'sknLblFontIconsffffff17px',
            LABEL_WHITE:'sknSSPLblFFFFFF15Px',
            LABEL_BLUE:'sknLabelSSP0273e315px',
            LABEL_MOVE_ACTIVE:'sknLabelSSP3343A821px',
            LABEL_MOVE_INACTIVE:'sknC0C0C021px',
            BREADCRUM2 : 'skna0a0a0op100breadcrumb2',
            PFM_CATEGORY_HOME : 'sknFEDB64PFM',
            PFM_CATEGORY_AUTO_TRANSPORT : 'skn3645A7PFM',
            PFM_CATEGORY_FINANCIAL : 'skn6753ECPFM',
            PFM_CATEGORY_FOOD_DINING : 'sknD6B9EAPFM',
            PFM_CATEGORY_BILLS_UTILITIES : 'sknE87C5EPFM',
            PFM_CATEGORY_TRAVEL : 'skn8ED174PFM',
            PFM_CATEGORY_HEALTH_FITNESS :'skn04B6DFPFM',
            PFM_CATEGORY_EDUCATION : 'sknE8A75EPFM',
            PFM_CATEGORY_OTHER :'sknB160DCPFM',
            PFM_CATEGORY_DEFAULT : 'skn23A8B1PFM',
            PFM_ACCOUNTS_LOAN : 'sknFlx8D6429',
            PFM_FLXACCOUNTS_SKIN : 'sknFlxFFFFFbrdr3343a8',
            PFM_TRANSACTIONSUNCATEGORIZED : 'sknFFFFFFmodbr4pxbebebeshdw',
            PFM_CATEGORIZEDMONTHLYSPENDING_BTNUNCATEGORIXED : 'sknBtnAccountSummarySelectedmod',
            PFM_CATEGORIZEDMONTHLYSPENDING_BTNCATEGORIZED : 'sknBtnAccountSummaryUnselectedTransfer424242',
            PFM_LBLIDENTIFIER : 'sknflx4a902',
            PFM_BTN_ENABLE : 'sknBtnNormalSSPFFFFFF15Px',
            PFM_BTN_ENABLE_FOCUS: 'sknBtnHoverSSPFFFFFF15Px',
            PFM_BTN_ENABLE_HOVER: 'sknBtnFocusSSPFFFFFF15Px',
            FONT_ICON_BLUE_21PX: 'sknLabelSSP0273e321px',
            TRANSFERS_TEXTBOX_NOERROR:'CopysknSSP0e30a26ff0c5f44',
            COMMON_CALENDAR_NOERROR:'sknCalNormal',
            COMMON_LISTBOX_NOERROR:'sknlbx15SSPe424242Border3e3e3Radius2px',
            COMMON_FLEX_NOERROR:'sknBorder727272',
            COMMON_FLEX_NOERRORSKIN:'sknBorder727272bgffffff',
            LOANS_LISTBOX_NOERROR:'sknlbx15SSPe424242Border3e3e3Radius2px',
            LOANS_LISTBOX_ERROR:'sknflxffffffborder727272opa20',
            LOANS_FLEX_ERROR:'sknborderff0000error',
            LOANS_LISTBOX_ERRORSKIN:'sknlstff0000disable',
            LOANPAYOFF_SKIN : 'sknFlxffffffShadowdddcdc',
            LOANDUE_CALENDER_NORMAL : 'sknCalBrdre3e3e3Backgrndfffff',
            PFM_BTN_SKIN : 'sknBtnSSPBg0273e3Border0273e3',
            ACTIVE_STATUS_SKIN : 'sknStatusActivatedUM',
            SUSPENDED_STATUS_SKIN : 'sknStatusSuspendedUM',
            NEW_STATUS_SKIN : 'sknStatusNewUM',
            DEACTIVATE_STATUS_SKIN : 'sknStatusDeactivatedUM',
            CHECKBOX_UNSELECTED_SKIN : 'skn0273e320pxolbfonticons',
            CHECKBOX_SELECTED_SKIN : 'sknFontIconCheckBoxSelected',
            LABEL_HEADER_BOLD : 'sknLblSSP42424215pxBold',
            FLEX_UNSELECTED_SKIN : 'sknBorderE3E3E3',
          	LABEL_GREY_15PX : 'sknSSP72727215Px',
          	LABEL_GREY_13PX : 'sknSSP72727213Px',
          	RTEXT_ERROR_MOBILE : 'sknRtxSSPFF000017Px',
          	RTEXT_ERROR_DESKTOP : 'sknRtxSSPFF000015Px',
          	NON_EDITABLETEXTBOX : 'sknSSP42424215BgD3D3D3Op10BorderE3E3E3',
            EDITABLE_TEXTBOX : 'sknSSP42424215PxBorder4A90E2',
            EXECUTED : 'skn04aa16fonticon20px',
            PENDING : 'sknffa500fonticon20px',
            FAILED : 'skn424242fonticon20px',
            DENIED : 'sknff0000fonticon20px',
        	BUSINESS_ENROLL_DEF : 'CopysknBB1',
            NEXT_BTN  :'sknBtnffffffBorder0273e31pxRadius2px',
            SWITCH_ON: 'sknfonticontoggleON45px',
            SWITCH_OFF: 'skna0a0a0fonticon45px',
            ACH_NEXT_BUTTON_SKIN : "sknBBBtn4",
            ACH_NEXT_BUTTON_WHITE_SKIN : "sknBtnffffffBorder0273e31pxRadius2px",
          	TAB_SELECTED :"sknBtnSSPSemiboldSelected",
            FLEX_ERROR_SKIN:"SknFlxBorderee0005Radius3Px",
            FLEX_NOERROR_SKIN:"bbSknFlxBordere3e3e3Radius3Px",
          	DRP_DWN_OTHER:"sknLblFontTypeIcon1a98ff12pxOther",
			RADIOBTN_DISABLE_SKIN: "sknFontIconDisabled",
			RADIOBTN_ENABLE_SKIN: "sknRadioselectedFonticon",
            BULKPAYMENTS_HEADER_SKIN: "bbSKnFlxffffff",
            BULKPAYMENTS_SECTION_SKIN: "sknlbl424242bold15px",
            ACKNOWLEDGEMENT_SKIN: "sknRtxSSPLight42424224Px",
			BULKPAYMENTS_HYPERLINK_SKIN: "sknLblSSP42424215pxBoldUnderline",
            BULKPAYMENTS_NOHYPERLINK_SKIN: "bbSknLbl424242SSP15Px",
          	BULKPAYMENTS_DROP_DOWN_SKIN: "ICSknLblDropdownFontIcon003e7518px",
            BULKPAYMENTS_FOCUS_SKIN: "bbSknFlxf9f9f9",
            BULKPAYMENTS_TEXTBOX_GREYED: "sknSSP42f8f7f8PxBorderE3E3E3",
            BULKPAYMENTS_TEXTBOX_DEFAULT: "sknSSP42424215PxBorderE3E3E3",
            BULKPAYMENTS_LISTBOX_GREYED: "sknlbx15SSPef8f7f8Border3e3e3Radius2px",
            BULKPAYMENTS_LISTBOX_DEFAULT: "sknlbx15SSPe424242Border3e3e3Radius2px",
            BULKPAYMENTS_SEARCHBOX_NORMAL: "bbSknTbx949494SSP15pxNormal",
            BULKPAYMENTS_BEN_LABEL_SKIN: "sknLbl4176a415px",
            BULKPAYMENTS_VIEWTYPE_LABEL: "ICSknBBLabelSSP42424215px",
            CURSOR_SKIN: "skncursor",
            HAMBURGER_HOVER_SKIN: "sknFlxHoverHamburger",
            HAMBURGER_UNSELECTED_SKIN:"sknLblHamburgerUnSelected",
            HAMBURGER_SELECTED_SKIN:"sknLblHamburgerSelected"
         },
        FONT_ICONS: {
            RADIO_BUTTON_SELECTED: "R",
            RADIO_BUTTON_UNSELECTED: " ",
            RADIO_BUTTON_UNSELECTED_NUO: "L",
            RADIO_BUTTON_SELECTED_NUO: "M",
            CHECBOX_SELECTED: "C",
            CHECBOX_UNSELECTED: "D",
            THREE_DOTS_ACCOUNTS : "O",
            FAVOURITE_STAR_ACTIVE: "F",
            FAVOURITE_STAR_INACTIVE: "k",
            CHECK_BOX_ICON: "V",
            LABEL_IDENTIFIER: "A",
            DISABLE_DOWN: "B",
            CHEVRON_DOWN:"O",
            CHEVRON_UP:"P",
            PENDING:"l",
            FAILED:"E",
            DENIED:"m",
            EXECUTED:"k"
        },
		PFM_CATEGORIES_COLORS : 
        {
            "Home": "#FEDB64",
            "Transport": "#3645A7",
            "Financial ": "#6753EC",
            "Food": "#D6B9EA",
            "Utilities": "#E87C5E",
            "Health": "#04B6DF",
            "Education": "#E8A75E",
            "Other": "#B160DC",
            "Travel" : "#8ED174"
        },
        POSITIONAL_VALUES: {
            DP: 'dp',
            PX: 'px',
            PERCENTAGE: '%'
        },
        MAGIC_NUMBERS: {
            FRAME_HEIGHT: 40,
            LIMIT: 10,
            MAX_HOUR: 23,
            MAX_MINUTES: 59,
            MIN_2DIGIT_NUM: 10
        },
        ACTION:
        {
            PAY_A_BILL: 'Pay a Bill',
            MAKE_A_TRANSFER : 'Make A Transfer',
            PAY_A_PERSON_OR_SEND_MONEY: 'Send Money',
            PAY_DUE_AMOUNT: 'Pay Due Amount',
            PAYOFF_LOAN : 'Payoff Loan',
            STOPCHECKS_PAYMENT: 'Stop Check Payment',
            SCHEDULED_TRANSACTIONS : 'Scheduled Transactions',
            TRANSFER_MONEY: 'Transfer Money',
          	PAY_MONEY: 'Pay Money',
            VIEW_STATEMENTS: 'View Statements',
            UPDATE_ACCOUNT_SETTINGS: 'Update Account Settings',
            REMOVE_ACCOUNT: 'Remove Account',
            ACCOUNT_PREFERENCES: 'Account Preferences',
            EDIT_ACCOUNT: 'Edit Account',
            SHOW_STOPCHECKS_FORM: 'ShowStopChecksForm',
          	REQUEST_CHEQUE_BOOK:  'Request Cheque Book',
          	REQUEST_CHEQUE_BOOK_FORM: 'showRequestChequeBookForm',
            SAVINGS_POT : 'Savings Pot',
            SHOW_DISPUTE_LIST: 'Disputed Transactions'
        },
        CONFIG : {
            ACCOUNTS_QUICK_ACTIONS: {
                "Savings": [
                    "Transfer Money",
                    "Pay Money",
                    "Stop Check Payment",
                    "View Statements",
                    "Refresh Account",
                    "Remove Account"
                ],
                "Checking": [
                    "Transfer Money",
                  	"Pay Money",
                    "Send Money",
                    "Pay a Bill",
                    "Stop Check Payment",
                    "View Statements",
                    "Refresh Account",
                    "Remove Account"
                ],
                "CreditCard": [
                    "Pay a Bill",
                    "View Statements"
                ],
                "Loan": [
                    "Pay Due Amount",
                    "View Statements",
                    "Update Account Settings"
                ],
                "Line of Credit": [
                    "View Statements",
                    "Update Account Settings"
                ],
                "Mortgage": [
                    "View Statements",
                    "Update Account Settings"
                ],
                "Deposit": [
                    "View Statements",
                    "Update Account Settings"
                ]
            },
            EXTERNAL_ACCOUNT_QUICK_ACTIONS:[
                "Remove Account",
                "Account Preferences",
                "Edit Account"
            ]
        },
        ALERTS_INPUT_TYPES:{
            "Range":"Range",
            "List":"List",
            "EqualTo":"EqualTo",
            "NoInputNeeded":"NoInputNeeded"
        },
        BULKWIRE_STATUS_TYPES:{
            "Pending":"Pending",
            "Failed":"Failed",
            "Denied":"Denied",
            "Executed":"Executed",
            "All":"All",
            "Rejected":"Rejected"
        },
      INFINITY_LOGOS:{
        "RB" : "kony_logo.png",
        "SME" : "sbb.png",
        "MBB" : "mbb.png",
        "GENERIC" : "digital_banking.png"
      },
      DAYS:{
          "Monday":"Monday",
          "Tuesday": "Tuesday",
          "Wednesday": "Wednesday",
          "Thursday": "Thursday",
          "Friday": "Friday",
          "Saturday":"Saturday",
          "Sunday":"Sunday"
      }
    };
    

    return VIEW_CONSTANTS;
});
